### ISSUE TITLE
Typo in GitHub pages model zoo

### ISSUE THREAD

**Issue by tyleransom** [dell-research-harvard/linktransformer#1]
Hi, I just wanted to report a minor typo I noticed on the GitHub pages "model zoo" page.

Under "Company Alias linkage", the link "dell-research-harvard/lt-wikidata-comp-es" says it is English, but this should be Spanish.

I would have submitted a pull request but it appears that the underlying repo for the GitHub page is not public.

**Comment by econabhishek** [comment]
Thank you! Fixed.
