### ISSUE TITLE
KeyError: 'metric' when running cluster_rows

### ISSUE THREAD

**Issue by robroc** [dell-research-harvard/linktransformer#10]
New user of LinkTransformer here. I ran `cluster_rows` on a dataframe of government contracts with a lot of variation on how vendors are written and got a KeyError. Dataframe is around 10,000 rows.

Other system info:

Windows 10
Python 3.10.11
linktransformer 0.1.11

Here's the full trace:

```
KeyError                                  Traceback (most recent call last)
Cell In[111], line 1
----> 1 clusters = lt.cluster_rows(contracts, on = 'vendor_name', cluster_params={'threshold': 0.7}, model = 'all-MiniLM-L6-v2')

File ~\miniconda3\envs\data\lib\site-packages\linktransformer\infer.py:390, in cluster_rows(df, model, on, cluster_type, cluster_params, openai_key)
    388 embeddings = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)
    389 ### Now, cluster the embeddings based on similarity threshold
--> 390 labels = cluster(cluster_type, cluster_params, embeddings, corpus_ids=None)
    391 ### Now, keep only 1 row per cluster
    392 df["cluster"] = labels

File ~\miniconda3\envs\data\lib\site-packages\linktransformer\modified_sbert\cluster_fns.py:61, in cluster(cluster_type, cluster_params, corpus_embeddings, corpus_ids)
     50     clustering_model = AgglomerativeClustering(
     51         n_clusters=None,
     52         distance_threshold=cluster_params["threshold"],
     53         linkage=cluster_params["clustering linkage"],
     54         metric=cluster_params["metric"]
     55     )
     57 if cluster_type == "SLINK":
     58     clustering_model = DBSCAN(
     59         eps=cluster_params["threshold"],
     60         min_samples=cluster_params["min cluster size"],
---> 61         metric=cluster_params["metric"]
     62     )
     64 if cluster_type == "HDBScan":
     65     clustering_model = hdbscan.HDBSCAN(
     66         min_cluster_size=cluster_params["min cluster size"],
     67         min_samples=cluster_params["min samples"],
     68         gen_min_span_tree=True
     69     )

KeyError: 'metric'
```

**Comment by econabhishek** [comment]
Thank you! This is due to some missing defaults for the "metric" parameter. I would suggest modifying the function call to 
lt.cluster_rows(contracts, on = 'vendor_name', cluster_params={'threshold': 0.7, "metric":"cosine"}, model = 'all-MiniLM-L6-v2')

I will add fixes for this in a new version which is coming soon.

**Comment by robroc** [comment]
Thank you @econabhishek! That solved the KeyError. Oddly, using the wikidata model assigned every company name to the same cluster. I'll wait for more documentation and tutorials on this before experimenting further with clustering.

**Comment by econabhishek** [comment]
No best threshold works for all cases - make sure to tune it!

**Comment by econabhishek** [comment]
The only proper way to do this would be to do this would be to prepare a validation set (say 15% of the data)- a set of labels where you know the the cluster membership of each firm, and then try to choose parameters that maximise a clustering quality metric like the ARI (kind of what we do in the work in progress tutorial notebook). For SLINK, go lower to get smaller clusters. 

Clustering 10k rows ( their embeddings) shouldn't take very long. As it stands, for now, only embedding is supported on GPU - which is super quick. We are trying to support end-to-end GPU use, but dependency management gets trickier. One more immediate suggestion would be to try moving the process to colab and see if you see the same behaviour. We only officially try to support Linux and more specifically colab.

**Comment by robroc** [comment]
This is incredibly helpful. Thank you so much for the advice and thank you for sharing such a useful and game-changing tool for working with messy data.

**Comment by econabhishek** [comment]
The issue has been fixed in the new version. Please update the package. 
We will work on more clustering techniques in the near future. 

Closing!
