### ISSUE TITLE
Parameter "suffixes" does not work for lt.merge()

### ISSUE THREAD

**Issue by soap293** [dell-research-harvard/linktransformer#11]
Hi, I am using the lt.merge() to link 2 dataframes.

`merged_df = lt.merge(df1, df2,
                     merge_type='1:1',
                     on='product',
                     model='dell-research-harvard/lt-wikidata-comp-zh',
                     suffixes=('_1', '_2'))`

This worked out fine, but the parameter "suffixes" does not look like it is working. 
The column names are still named after "_x" and "_y" as default.
This is a minor issue though.
Thanks for sharing this great module!

**Comment by econabhishek** [comment]
Thanks! Noting this down for the next feature update since it's not urgent.

**Comment by econabhishek** [comment]
Fixed with v 0.1.13
