### ISSUE TITLE
Fixing `dedup_rows` example

### ISSUE THREAD

**Issue by kerenganon** [dell-research-harvard/linktransformer#5]
Hey, thanks for sharing this!

Small note - the README.md mentioned the following example for calling `dedup_rows` which fails:
```python
deduplicated_df = lt.dedup_rows(df, model='your-pretrained-model', on='text_column', threshold=0.8)
```

I suggest changing to the one in [infer_test](https://github.com/dell-research-harvard/linktransformer/tree/4873e628cd72a01c37678e6daa7b1f2b6072c266/tests/infer_test.py)

```python
deduplicated_df = lt.dedup_rows(df, model='your-pretrained-model', on='text_column', cluster_type='preferred_cluster_type', cluster_params= {'threshold': 0.8})
```

**Comment by econabhishek** [comment]
Fixed, thank you!
